language: node_js
cache: npm

env:
  - THREADS_WORKER_INIT_TIMEOUT=15000

stages:
  - name: test
  - name: publish
    if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+/

jobs:
  include:
    - stage: test
      os: linux
      addons:
        chrome: stable
      node_js: "8.12"
      script: npm test

    - stage: test
      os: linux
      addons:
        chrome: stable
      node_js: node
      script: npm test

    - stage: test
      os: windows
      addons:
        grep: stable
      filter_secrets: false  # Secrets will otherwise break Windows builds
      node_js: "8.12"
      env:
        - THREADS_WORKER_INIT_TIMEOUT=30000
      script: npm run test:ava

    - stage: test
      os: windows
      addons:
        grep: stable
      filter_secrets: false  # Secrets will otherwise break Windows builds
      node_js: latest
      env:
        - THREADS_WORKER_INIT_TIMEOUT=30000
      script: npm run test:ava

    - name: publish to latest
      stage: publish
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/
      node_js: node
      os: linux
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - npm version $(echo $TRAVIS_TAG | sed s/^v//) --allow-same-version
        - npm publish $(npx teleprompt --output-format cli --prompt 'otp:otp:2FA Token')

    - name: publish to testing
      stage: publish
      if: tag =~ /^v?[0-9]+\.[0-9]+\.[0-9]+-test/
      node_js: node
      os: linux
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - npm version $(echo $TRAVIS_TAG | sed s/^v//) --allow-same-version
        - npm publish --tag=testing $(npx teleprompt --output-format cli --prompt 'otp:otp:2FA Token')
